# Generated by Django 4.2 on 2023-05-06 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.book'),
        ),
    ]
