# Generated by Django 4.2 on 2023-05-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_book_image_alter_bookclub_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='bookclub',
            name='language',
        ),
        migrations.RemoveField(
            model_name='bookpage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='clubpage',
            name='language',
        ),
    ]
