# Generated by Django 4.2 on 2023-05-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_remove_book_language_remove_bookclub_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='venue',
            field=models.CharField(default='Online', max_length=200, null=True),
        ),
    ]
