# Generated by Django 4.2 on 2023-05-11 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0005_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='members',
            field=models.ManyToManyField(related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
