# Generated by Django 4.2 on 2023-05-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_want_to_read',
            field=models.BooleanField(default=False),
        ),
    ]
