# Generated by Django 4.2 on 2023-05-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_book_is_read_book_is_want_to_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_read',
            field=models.DateField(blank=True, null=True),
        ),
    ]
