# Generated by Django 4.2 on 2023-05-18 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0010_book_average_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_read',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_want_to_read',
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_want_to_read', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('date_read', models.DateField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
