# Generated by Django 4.2 on 2023-05-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_remove_book_date_read_remove_book_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='status',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
