# Generated by Django 4.2 on 2023-05-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_userbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.userbook'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
