# Generated by Django 4.2 on 2023-05-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
