# Generated by Django 4.2 on 2023-05-22 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_bookclub_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='selected_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_clubs', to='club.book'),
        ),
    ]
