# Generated by Django 4.2 on 2023-05-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0018_bookclub_selected_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bookclub',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.book'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='meeting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.meeting'),
        ),
    ]
