# Generated by Django 4.2 on 2023-05-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0020_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='book_queue',
            field=models.ManyToManyField(related_name='queued_clubs', to='club.book'),
        ),
    ]
