# Generated by Django 4.2 on 2023-05-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0021_bookclub_book_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubpage',
            name='book_club',
        ),
        migrations.RemoveField(
            model_name='bookclub',
            name='book',
        ),
        migrations.DeleteModel(
            name='BookPage',
        ),
        migrations.DeleteModel(
            name='ClubPage',
        ),
    ]
