# Generated by Django 4.2 on 2023-05-26 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0024_bookclub_book_queue_members_queue_book_queue_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookclub',
            name='book_queue',
        ),
        migrations.AlterField(
            model_name='queue',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
