# Generated by Django 4.2 on 2023-05-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0025_remove_bookclub_book_queue_alter_queue_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='book_queue',
            field=models.ManyToManyField(related_name='queued_clubs', through='club.Queue', to='club.book'),
        ),
    ]
