# Generated by Django 4.2 on 2023-05-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0026_bookclub_book_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='location_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
