# Generated by Django 4.2 on 2023-06-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0027_remove_bookclub_meeting_bookclub_meetings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookclub',
            name='meetings',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='club.bookclub'),
        ),
    ]
