# Generated by Django 4.2 on 2023-06-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0028_remove_bookclub_meetings_alter_meeting_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='club',
        ),
        migrations.AddField(
            model_name='meeting',
            name='clubs',
            field=models.ManyToManyField(related_name='meetings', to='club.bookclub'),
        ),
    ]
