# Generated by Django 4.2 on 2023-06-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0029_remove_meeting_club_meeting_clubs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='clubs',
            new_name='club',
        ),
    ]
