# Generated by Django 4.2 on 2023-06-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0030_rename_clubs_meeting_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='theme',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
