# Generated by Django 4.2 on 2023-06-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0031_bookclub_genre_bookclub_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='theme',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
