# Generated by Django 4.2 on 2023-07-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0033_alter_userbook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
